### ISSUE TITLE
Story: Ticket Creation

### ISSUE THREAD

**Issue by simibac** [bc-ticketing/idetix#12]
As a HOST, I want to issue tickets for my event, so that I can start distributing tickets for the event.

### Acceptance Criteria
- [x] tickets can be issued
- [x] tickets can be sold
- [x] tickets price goes to the event host

------
### Implementation Tasks
- [x] smart contract implementation
- [x] smart contract integration in front end 

------
### Linked issues
- #6
