### ISSUE TITLE
Story: Different Ticket Categories

### ISSUE THREAD

**Issue by simibac** [bc-ticketing/idetix#13]
As a HOST, I want to define different ticket categories, so that I can sell different kinds of tickets and pricing options.

### Acceptance Criteria
- [ ] Indifferent tickets can be issued (fungible) eg. standing room area
- [ ] Unique tickets can be issued (non fungible) eg. ticket with seat number
- [ ] Fungible tickets can be sold
- [ ] Non fungible tickets can be sold

------
### Implementation Tasks
- [ ] smart contract implementation
- [ ] smart contract integration in front end 

------
### Linked issues
-
