### ISSUE TITLE
Story: Sale Statistics

### ISSUE THREAD

**Issue by simibac** [bc-ticketing/idetix#15]
As a HOST, I want to have insights on sale statistics, so that I can see how many tickets are already sold.

### Acceptance Criteria
- [ ] data on how many tickets have been sold is available

------
### Implementation Tasks
- [ ] smart contract implementation
- [ ] smart contract integration in front end 

------
### Linked issues
-
