### ISSUE TITLE
Story: Aftermarket

### ISSUE THREAD

**Issue by simibac** [bc-ticketing/idetix#18]
As a HOST, I want to have control over the aftermarket, so that tickets cannot be sold for a higher price than the original price.

### Acceptance Criteria
- [ ] tickets cannot directly be transferred from one user to another
- [ ] tickets can only be sold back to the smart contract
- [ ] tickets cannot be sold for higher prices

------
### Implementation Tasks
- [ ] smart contract implementation
- [ ] smart contract integration in front end 

------
### Linked issues
- https://github.com/bc-ticketing/idetix/issues/6
