### ISSUE TITLE
Story: Advertise Event

### ISSUE THREAD

**Issue by mialbu** [bc-ticketing/idetix#19]
As an Affiliate, I want to advertise an event, so that I can help event hosts to sell their event tickets.

### Acceptance Criteria

- [ ] affiliate can use a link to distribute
- [ ] address of affiliate is integrated into ticket purchase when calling the link

------
### Implementation Tasks
- [ ] smart contract implementation
- [ ] smart contract integration in front end 

------
### Linked issues
-
