### ISSUE TITLE
Story: Identity Providers

### ISSUE THREAD

**Issue by simibac** [bc-ticketing/idetix#22]
As a HOST, I want to define what identity service is secure enough for me, so that I align it with our entrance policies and controls.

### Acceptance Criteria
- [ ] identity approvers offer multiple options for verifications (Onfido, Airbnb, etc)

------
### Implementation Tasks
- [ ] identity smart contract implementation
- [ ] verification script for automatically push a proof to the blockchain, when the identity provider verifies a user

------
### Linked issues
-
