### ISSUE TITLE
Story: Presale lottery

### ISSUE THREAD

**Issue by mialbu** [bc-ticketing/idetix#24]
As a guest, I want to take part in the presale lottery, so that I have a fair chance of getting a high stake ticket.

### Acceptance Criteria

- [x] guests can buy a lottery ticket (for ticket price) before the regular sale starts.

------
### Implementation Tasks
- [x] smart contract implementation
- [x] smart contract integration in front end 

------
### Linked issues
- #4
