### ISSUE TITLE
Story: Ticket Invalidation

### ISSUE THREAD

**Issue by simibac** [bc-ticketing/idetix#25]
As a HOST, I want to invalidate tickets, so that I can tell which ticket has been used already.

### Acceptance Criteria
- [ ] a ticket cannot be used twice
- [ ] tickets cannot be sold after the guest has entered the venue

------
### Implementation Tasks
- [ ] off-chain host backend implementation
- [ ] display ticket invalidations in host frontend

------
### Linked issues
-
