### ISSUE TITLE
Story: Access Control

### ISSUE THREAD

**Issue by simibac** [bc-ticketing/idetix#26]
As a HOST, I want to have fluid entrance controls, so that my customers don't have to wait in line for too long.

### Acceptance Criteria
- [ ] off-chain host backend 
- [ ] ticket owners can be read from smart contract
- [ ] proof of identification is simple

------
### Implementation Tasks
- [ ] off-chain host backend keeping track which tickets have entered
- [ ] host backend runs a blockchain node
- [ ] qr-code reader mobile app for fast identification proof 
- [ ] qr-code reader connects to host backend

------
### Linked issues
-
