### ISSUE TITLE
Story: Resell Withdrawal

### ISSUE THREAD

**Issue by mialbu** [bc-ticketing/idetix#29]
As a Guest, I want to be able to withdraw my resell offer, so that I can keep my ticket, when I no longer want to sell it.

### Acceptance Criteria

- [x] unfilled (not sold) ticket resell offers can be withdrawn

------
### Implementation Tasks
- [x] smart contract implementation
- [x] smart contract integration in front end 

------
### Linked issues
-
