### ISSUE TITLE
Story: Area Control

### ISSUE THREAD

**Issue by simibac** [bc-ticketing/idetix#30]
As a HOST, I want to have control over who is where on the event area, so that I can have a clear view of the event for security and crowd control.

### Acceptance Criteria
- [ ] users are tracked when entering different areas on the venue

------
### Implementation Tasks
- [ ] areas can be added to the host backend
- [ ] tickets are labelled with an area
- [ ] access control scanners are configured with an area which is accessed

------
### Linked issues
-
