### ISSUE TITLE
Story: Re-Entrance

### ISSUE THREAD

**Issue by simibac** [bc-ticketing/idetix#34]
As a HOST, I want to be able to manage re-entrance, so that my customers can leave and re-enter the event.

### Acceptance Criteria
- [ ] re-entrance is configurable for each venue

------
### Implementation Tasks
- [ ] host backend allows a configuration which enables or disables if a user can reenter after leaving the venue
- [ ] frontend: display if the ticket can be used to reenter the venue

------
### Linked issues
-
