### ISSUE TITLE
Story: Resell Ticket

### ISSUE THREAD

**Issue by mialbu** [bc-ticketing/idetix#35]
As a Guest, I want to be able to sell my owned ticket, so that I can mitigate my loss when I cannot or no longer want to go to the event.

### Acceptance Criteria

- [x] owned tickets can be offered for sale
- [x] upon sale, ticket price is directly transferred to seller address

------
### Implementation Tasks
- [x] smart contract implementation
- [x] smart contract integration in front end 

------
### Linked issues
-
