### ISSUE TITLE
Story: Presale

### ISSUE THREAD

**Issue by simibac** [bc-ticketing/idetix#37]
As a HOST, I want to be able to define a start-time of the regular ticket sale, so that guests can register for a presale lottery to get fair chances for a high stake ticket.

### Acceptance Criteria
- [ ] lottery cannot be manipulated
- [ ] lottery outcome is publicly available
- [ ] host can issue lottery tickets
- [ ] unsold tickets in the presale are available through normal ticket sale
- [ ] ticket price for presale can be configured
- [ ] only verified owner can buy tickets
- [ ] tickets are linked to identity
------
### Implementation Tasks
- [ ] presale smart contract smart contract implementation
- [ ] research on randomness options in a smart contract
- [ ] frontend integration for joining presale

------
### Linked issues
-
