### ISSUE TITLE
Story: Cloud Wallet Provider

### ISSUE THREAD

**Issue by simibac** [bc-ticketing/idetix#38]
As a GUEST, I want to use a cloud wallet provider, so that I don't have to install any additional apps and I don't need to deal with private keys.

### Acceptance Criteria
- [ ] no additional app is needed to buy a ticket
- [ ] frontend offers multiple options to connect an Ethereum wallet
- [ ] frontend automatically detects whether a user accesses the app from mobile and only displays possible wallet options
------
### Implementation Tasks
- [ ] Research Fortmatic (https://fortmatic.com/)
- [ ] Research Portis (https://docs.portis.io/#/)
- [ ] Research Bitski (https://www.bitski.com/)
- [ ] integrate selected wallet providers with their API
------
### Linked issues
-
