### ISSUE TITLE
Story: Buy a Ticket

### ISSUE THREAD

**Issue by mialbu** [bc-ticketing/idetix#51]
As a Guest, I want to be able to buy a ticket for an event, so that I can participate at this event.

### Acceptance Criteria

- [x] after ticket is bought, the ticket is linked to the buyer's address
- [x] frontend shows ticket in inventory after acquisition

------
### Implementation Tasks
- [x] smart contract implementation
- [x] smart contract integration in front end 

------
### Linked issues
-
